[project]
name = "spam-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "addict>=2.4.0",
    "einops>=0.8.1",
    "emoji>=2.15.0",
    "faiss-cpu>=1.13.1",
    "joblib>=1.5.3",
    "langchain-community>=0.4.1",
    "langchain-huggingface>=1.2.0",
    "mlflow>=3.7.0",
    "mysql-connector-python>=9.5.0",
    "numpy>=2.3.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "prefect>=3.6.6",
    "pymysql>=1.1.2",
    "pytest>=9.0.2",
    "pyyaml>=6.0.3",
    "sentence-transformers>=5.2.0",
    "sqlalchemy>=2.0.45",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
    "xgboost>=3.1.2",
]
