server:
  source: 'mysql'
  host: "10.168.51.196"
  port: 3306
  user: 'unified'
  password: 'unified'

data:
  query: 
    'SELECT 
      `payload_length`,
      `payload` 
    FROM 
      sms_spam_cd.data_tdr_spam_filter 
    LIMIT 10000'
  column_name: ['message_length',  'message'] # need to match the number of columns from `query`
  target_column: 'message'
  drop_null: True
  drop_duplicates: False

models:
  text_embedding:
    model_name: 'jinaai/jina-embeddings-v3'
    batch_size: 16
  
  spam_detection:
    model_name: 'mariagrandury/distilbert-base-uncased-finetuned-sms-spam-detection'
    model_type: 'text-classification'