# server configuration
server: 
  source: 'mysql'
  host: "10.168.51.196"
  port: 3306
  user: 'unified'
  password: 'unified'

# setup progress log
progress_log: 
  folder: 'logs/progress'
  files:
    finished: 'logs/progress/label_metadata.xlsx'
    unfinished: 'logs/progress/unlabel_metadata.xlsx'

# define model to perform spam detection
models: 
  text_embedding:
    model_name: "jinaai/jina-embeddings-v3"
    batch_size: 8
  confidence_score_threshold: 0.9
  save_model_to:
    folder: 'models'
 
# quert to select subdata
data:
  query: 
    'SELECT 
      id,
      current_datetime,
      payload
    FROM 
      sms_spam_cd.data_tdr_spam_filter 
    WHERE
      YEAR(current_datetime) = {}
      AND MONTH(current_datetime) = {}
      AND DAY(current_datetime) = {}
      AND HOUR(current_datetime) = {}'
  column_name: ['id', 'datetime', 'payload']
  target_column: 'payload' # specific the main column that listed in `column_name`
  metadata_column: ['id', 'datetime']

# define population data's metadata
metadata:
  query: 
    'SELECT DISTINCT
      YEAR(current_datetime), 
      MONTH(current_datetime), 
      DAY(current_datetime), 
      HOUR(current_datetime)
    FROM 
      sms_spam_cd.data_tdr_spam_filter'
  column_name: ['year', 'month', 'day', 'hour'] 

# define data to initialize model 
initialize_model:
  query: 
    'SELECT 
      ml.embedding, 
      ml.spam_label_update 
    FROM 
      sms_spam_cd.ml_spam_result_ori ml
      LEFT JOIN sms_spam_cd.data_tdr_spam_filter data on ml.id = data.id 
    WHERE 
      day(data.current_datetime) = 16 
      and hour(data.current_datetime) = 0'

# define where vectorstores locate
vectorstore:
  directory: './data/vector'
  filename: 'sms_embeddings'

# define experiment and model name for this project
mlflow_config:
  experiment_name: 'SMS SPAM DETECTION'
  model_name: 'sgd_model'