server: # server configuration
  source: 'mysql'
  host: "10.168.51.196"
  port: 3306
  user: 'unified'
  password: 'unified'


data:
  query: # the dataset import into python module
    'SELECT 
      `payload_length`,
      `payload` 
    FROM 
      sms_spam_cd.data_tdr_spam_filter 
    WHERE
      YEAR(current_datetime) = {}
      AND MONTH(current_datetime) = {}
      AND DAY(current_datetime) = {}
      AND HOUR(current_datetime) = {}'
  column_name: ['message_length', 'message']
  target_column: 'message' # specific the main column that listed in `column_name`
  drop_null: false
  drop_duplicates: false


models: # define model to perform spam detection
  text_embedding:
    model_name: 'jinaai/jina-embeddings-v3'
    batch_size: 32
  
  spam_detection:
    model_name: 'mariagrandury/distilbert-base-uncased-finetuned-sms-spam-detection'
    model_type: 'text-classification'
    labelling_confidence_threshold: 0.99
  

active_learning:
  subdata_metadata_query: # define subdata group, active learning will loop through group by group
    'SELECT DISTINCT
      YEAR(current_datetime), 
      MONTH(current_datetime), 
      DAY(current_datetime), 
      HOUR(current_datetime) 
    FROM 
      sms_spam_cd.data_tdr_spam_filter'
  column_name: ['year', 'month', 'day', 'hour']
  

module_log:
  path: './logs'