server:
  source: 'mysql'
  mysql_host: "10.168.51.196"
  mysql_port: 3306
  mysql_user: 'unified'
  mysql_password: 'unified'

data:
  query: 
    'SELECT 
      `smsc_src_addr`, 
      `payload_length`,
      `payload` 
    FROM 
      sms_spam_cd.data_tdr_spam_filter 
    LIMIT 10000'
  column_name: ['from', 'message_length',  'message']