server: # server configuration
  source: 'mysql'
  host: "10.168.51.196"
  port: 3306
  user: 'unified'
  password: 'unified'


module_log: 
  process_log_path: 
    folder: 'logs/process'
    files:
      label_record_file: 'logs/process/label_metadata.xlsx'
      unlabel_record_file: 'logs/process/unlabel_metadata.xlsx'


models: # define model to perform spam detection
  text_embedding:
    model_name: 'jinaai/jina-embeddings-v3'
    batch_size: 8
  
  spam_detection:
    model_name: 'mrm8488/bert-tiny-finetuned-sms-spam-detection' 
    labelling_confidence_threshold: 0.90
    batch_size: 32 

  save_model_to:
    folder: 'models'
 

data:
  query: 
    'SELECT 
      id,
      payload
    FROM 
      sms_spam_cd.data_tdr_spam_filter 
    WHERE
      YEAR(current_datetime) = {}
      AND MONTH(current_datetime) = {}
      AND DAY(current_datetime) = {}
      AND HOUR(current_datetime) = {}'
  column_name: ['id', 'payload']
  target_column: 'payload' # specific the main column that listed in `column_name`
  vector_column: 'vector'


metadata:
  query: # define subdata group, active learning will loop through group by group
    'SELECT DISTINCT
      YEAR(current_datetime), 
      MONTH(current_datetime), 
      DAY(current_datetime), 
      HOUR(current_datetime)
    FROM 
      sms_spam_cd.data_tdr_spam_filter'
  column_name: ['year', 'month', 'day', 'hour']
  raw_message_folder: 'data/message' 
  message_vector_folder: 'data/vector'  


vectorstore:
  directory: '../vector'
  filename: 'sms_embeddings.bin'